#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


postgres_ready() {
python << END
import os
import sys
import psycopg2

try:
    psycopg2.connect(
        dbname=os.environ['DB_NAME'],
        user=os.environ['DB_USER'],
        password=os.environ['DB_PASS'],
        host=os.environ['DB_HOST'],
        port=os.environ['DB_PORT'],
    )
except psycopg2.OperationalError as e:
    print(e)
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
    echo 'Waiting for PostgreSQL to become available...'
    sleep 1
done
echo 'PostgreSQL is available'

exec "$@"
