[tool.isort]
profile = "black"

# [tool.black]
# line-length = 80

[tool.pytest.ini_options]
addopts = """
    -vv
    --exitfirst
    --new-first
    --durations=10
    --asyncio-mode=auto
    --cov=app
    -m='full'
"""
markers = [
    "smoke: smoke tests",
]
