"""add scope to Token table

Revision ID: 5e98574b3596
Revises: eb5a1d47bd32
Create Date: 2023-06-05 16:39:47.196840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e98574b3596'
down_revision = 'eb5a1d47bd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('scope', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'scope')
    # ### end Alembic commands ###
